VDW.VDWS.Local = VDW.VDWS.Local or (function()
	local base = {
		CLOSE_THIS_PANEL = "Close this panel!",
		OPTIONS_FOR = "Options for %s",
		
		FOUR_EDGES = "Four Edges",
		LOOTY_GROOVE = "Looty Groove",
		ERROR_FRAME_FPS = "Error Frame, FPS Frame, etc.",
		ERROR_FRAME = "Error Frame",
		FPS_FRAME = "FPS Frame",
		ET_CHETERA = "Et cetera",
		ARTWORK = "Artwork",
		SIZE = "Size",
		TOP_LEFT_EDGE_ARTWORK = "Top left edge artwork",
		BOTTOM_LEFT_EDGE_ARTWORK = "Bottom left edge artwork",
		TOP_RIGHT_EDGE_ARTWORK = "Top right edge artwork",
		BOTTOM_RIGHT_EDGE_ARTWORK = "Bottom right edge artwork",
		BACKGROUND = "Background",
		FONTS = "Fonts",
		TITLE = "Title",
		LOOT = "Loot",
		COINS = "Coins",
		CURRENCIES = "Currencies",
		EXPIRIENCE = "Experience",
		HONOR = "Honor",
		REPUTATION = "Reputation",
		SKILL = "Skill",
		MISCELLANEOUS = "Miscellaneous (Durability, Opening, etc.)",
		CHANGE_THE_ERROR_FRAME_FONTS = "Change the Error Frame fonts",
		VISIBILITY = "Visibility",
		STYLE = "Style",
		COLOR = "Color",
		CHAT_BACKGROUND = "Chat Background",
		WARNINGS = "Warnings",
		ERRORS = "Errors",
		SHOW_FPS = "Show FPS Frame",
		SHOW_MICROMENU = "Show Micro Menu Container Background",
		SHOW_BAR_TEXT = "Show XP/Reputation/Honor Bar Text",
		MAP_CLOCK = "Use 24-hour Map Clock",
		SHOW_CHAT_BACKGROUND = "Show Chat Background",
		
		VISIBILITY_TIP = "Do you want to show %s?",
		STYLE_TIP = "Which style do you want for %s?",
		COLOR_TIP = "Which color do you want for %s?",
		SIZE_TIP = "Which size do you want for %s?",
		
		CHECK_VISIBILITY_TIP_IN_THE = "Check me if you want %s to be shown in %s.",
		CHECK_VISIBILITY_TIP = "Check me if you want %s to be shown.",
		CHECK_IF_YOU_WANT_TO_TIP = "Check me if you want to %s.",
		
		SLIDER_TEXT_OPACITY  = "Opacity: %d",
		SLIDER_TEXT_VISIBILITY = "Text visible: %d sec",
		SLIDER_TIP = "You can also use the mouse wheel or the arrow buttons to change the value.",
		SLIDER_TEXT_HEIGHT = "Height: %d",
		SLIDER_TEXT_WIDTH  = "Width: %d",
		
		P_TAB = "Profiles",
		P_TITLE = "Create, Load, and Delete Profiles",
		P_SUB_CREATE = "Create Profiles",
		P_SUB_LOAD = "Load Profiles",
		P_SUB_DELETE = "Delete Profiles",
		P_SUB_NOTES = "Notes",

		P_TIP_CREATE = "Type a profile name and press Enter to save your settings.",
		P_TIP_LOAD = "Select a profile to load.",
		P_TIP_DELETE = "Select a profile to delete.",

		P_WRN_NEED = "Please enter a profile name.",
		P_WRN_EXIST = "That profile already exists. Please try another name.",
		P_WRN_LOAD = "There are no profiles to load.",
		P_WRN_DELETE = "There are no profiles to delete.",
	}
	local o = {
		esMX = {
			CLOSE_THIS_PANEL = "¡Cerrar este panel!",
			OPTIONS_FOR = "Opciones de %s",
			
			FOUR_EDGES = "Cuatro bordes",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Marco de errores, marco de FPS, etc.",
			ERROR_FRAME = "Marco de errores",
			FPS_FRAME = "Marco de FPS",
			ET_CHETERA = "etcétera",
			ARTWORK = "Arte",
			SIZE = "Tamaño",
			TOP_LEFT_EDGE_ARTWORK = "Arte del borde superior izquierdo",
			BOTTOM_LEFT_EDGE_ARTWORK = "Arte del borde inferior izquierdo",
			TOP_RIGHT_EDGE_ARTWORK = "Arte del borde superior derecho",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Arte del borde inferior derecho",
			BACKGROUND = "Fondo",
			FONTS = "Fuentes",
			TITLE = "Título",
			LOOT = "Botín",
			COINS = "Dinero",
			CURRENCIES = "Monedas",
			EXPIRIENCE = "Experiencia",
			HONOR = "Honor",
			REPUTATION = "Reputación",
			SKILL = "Habilidad",
			MISCELLANEOUS = "Miscelánea (durabilidad, apertura, etc.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Cambiar las fuentes del marco de errores",
			VISIBILITY = "Visibilidad",
			STYLE = "Estilo",
			COLOR = "Color",
			CHAT_BACKGROUND = "Fondo del chat",
			WARNINGS = "Advertencias",
			ERRORS = "Errores",
			SHOW_FPS = "Mostrar marco de FPS",
			SHOW_MICROMENU = "Mostrar fondo del contenedor del micromenú",
			SHOW_BAR_TEXT = "Mostrar texto de la barra de EXP/Reputación/Honor",
			MAP_CLOCK = "Usar reloj del mapa en 24 horas",
			SHOW_CHAT_BACKGROUND = "Mostrar fondo del chat",
			
			VISIBILITY_TIP = "¿Quieres mostrar %s?",
			STYLE_TIP = "¿Qué estilo quieres para %s?",
			COLOR_TIP = "¿Qué color quieres para %s?",
			SIZE_TIP = "¿Qué tamaño quieres para %s?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Márcame si quieres que %s se muestre en %s.",
			CHECK_VISIBILITY_TIP = "Márcame si quieres que %s se muestre.",
			CHECK_IF_YOU_WANT_TO_TIP = "Márcame si quieres %s.",
			
			SLIDER_TEXT_OPACITY  = "Opacidad: %d",
			SLIDER_TEXT_VISIBILITY = "Texto visible: %d s",
			SLIDER_TIP = "También puedes usar la rueda del ratón o los botones laterales para cambiar el valor.",
			SLIDER_TEXT_HEIGHT = "Alto: %d",
			SLIDER_TEXT_WIDTH  = "Ancho: %d",
			
			P_TAB = "Perfiles",
			P_TITLE = "Crear, cargar y eliminar perfiles",
			P_SUB_CREATE = "Crear perfiles",
			P_SUB_LOAD = "Cargar perfiles",
			P_SUB_DELETE = "Eliminar perfiles",
			P_SUB_NOTES = "Notas",

			P_TIP_CREATE = "Escribe un nombre de perfil y presiona Enter para guardar tus ajustes.",
			P_TIP_LOAD = "Selecciona un perfil para cargar.",
			P_TIP_DELETE = "Selecciona un perfil para eliminar.",

			P_WRN_NEED = "Por favor, escribe un nombre de perfil.",
			P_WRN_EXIST = "Ese perfil ya existe. Intenta con otro nombre.",
			P_WRN_LOAD = "No hay perfiles para cargar.",
			P_WRN_DELETE = "No hay perfiles para eliminar.",
		},
		ptBR = {
			CLOSE_THIS_PANEL = "Fechar este painel!",
			OPTIONS_FOR = "Opções de %s",
			
			FOUR_EDGES = "Quatro bordas",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Quadro de erros, quadro de FPS etc.",
			ERROR_FRAME = "Quadro de erros",
			FPS_FRAME = "Quadro de FPS",
			ET_CHETERA = "etc.",
			ARTWORK = "Arte",
			SIZE = "Tamanho",
			TOP_LEFT_EDGE_ARTWORK = "Arte da borda superior esquerda",
			BOTTOM_LEFT_EDGE_ARTWORK = "Arte da borda inferior esquerda",
			TOP_RIGHT_EDGE_ARTWORK = "Arte da borda superior direita",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Arte da borda inferior direita",
			BACKGROUND = "Plano de fundo",
			FONTS = "Fontes",
			TITLE = "Título",
			LOOT = "Saque",
			COINS = "Dinheiro",
			CURRENCIES = "Moedas",
			EXPIRIENCE = "Experiência",
			HONOR = "Honra",
			REPUTATION = "Reputação",
			SKILL = "Perícia",
			MISCELLANEOUS = "Diversos (durabilidade, abertura etc.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Alterar as fontes do quadro de erros",
			VISIBILITY = "Visibilidade",
			STYLE = "Estilo",
			COLOR = "Cor",
			CHAT_BACKGROUND = "Fundo do chat",
			WARNINGS = "Avisos",
			ERRORS = "Erros",
			SHOW_FPS = "Mostrar quadro de FPS",
			SHOW_MICROMENU = "Mostrar fundo do contêiner do micro menu",
			SHOW_BAR_TEXT = "Mostrar texto da barra de EXP/Reputação/Honra",
			MAP_CLOCK = "Usar relógio do mapa em 24 horas",
			SHOW_CHAT_BACKGROUND = "Mostrar fundo do chat",
			
			VISIBILITY_TIP = "Você quer mostrar %s?",
			STYLE_TIP = "Qual estilo você quer para %s?",
			COLOR_TIP = "Qual cor você quer para %s?",
			SIZE_TIP = "Qual tamanho você quer para %s?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Marque-me se quiser que %s apareça em %s.",
			CHECK_VISIBILITY_TIP = "Marque-me se quiser que %s apareça.",
			CHECK_IF_YOU_WANT_TO_TIP = "Marque-me se quiser %s.",
			
			SLIDER_TEXT_OPACITY  = "Opacidade: %d",
			SLIDER_TEXT_VISIBILITY = "Texto visível: %d s",
			SLIDER_TIP = "Você também pode usar a roda do mouse ou os botões laterais para mudar o valor.",
			SLIDER_TEXT_HEIGHT = "Altura: %d",
			SLIDER_TEXT_WIDTH  = "Largura: %d",
			
			P_TAB = "Perfis",
			P_TITLE = "Criar, carregar e excluir perfis",
			P_SUB_CREATE = "Criar perfis",
			P_SUB_LOAD = "Carregar perfis",
			P_SUB_DELETE = "Excluir perfis",
			P_SUB_NOTES = "Notas",

			P_TIP_CREATE = "Digite um nome de perfil e pressione Enter para salvar suas configurações.",
			P_TIP_LOAD = "Selecione um perfil para carregar.",
			P_TIP_DELETE = "Selecione um perfil para excluir.",

			P_WRN_NEED = "Digite um nome de perfil.",
			P_WRN_EXIST = "Esse perfil já existe. Tente outro nome.",
			P_WRN_LOAD = "Não há perfis para carregar.",
			P_WRN_DELETE = "Não há perfis para excluir.",
		},
		frFR = {
			CLOSE_THIS_PANEL = "Fermer ce panneau !",
			OPTIONS_FOR = "Options pour %s",
			
			FOUR_EDGES = "Quatre bords",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Cadre d’erreurs, cadre FPS, etc.",
			ERROR_FRAME = "Cadre d’erreurs",
			FPS_FRAME = "Cadre FPS",
			ET_CHETERA = "etc.",
			ARTWORK = "Graphisme",
			SIZE = "Taille",
			TOP_LEFT_EDGE_ARTWORK = "Graphisme du bord supérieur gauche",
			BOTTOM_LEFT_EDGE_ARTWORK = "Graphisme du bord inférieur gauche",
			TOP_RIGHT_EDGE_ARTWORK = "Graphisme du bord supérieur droit",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Graphisme du bord inférieur droit",
			BACKGROUND = "Arrière-plan",
			FONTS = "Polices",
			TITLE = "Titre",
			LOOT = "Butin",
			COINS = "Argent",
			CURRENCIES = "Monnaies",
			EXPIRIENCE = "Expérience",
			HONOR = "Honneur",
			REPUTATION = "Réputation",
			SKILL = "Compétence",
			MISCELLANEOUS = "Divers (durabilité, ouverture, etc.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Changer les polices du cadre d’erreurs",
			VISIBILITY = "Visibilité",
			STYLE = "Style",
			COLOR = "Couleur",
			CHAT_BACKGROUND = "Fond du chat",
			WARNINGS = "Avertissements",
			ERRORS = "Erreurs",
			SHOW_FPS = "Afficher le cadre FPS",
			SHOW_MICROMENU = "Afficher l’arrière-plan du conteneur du micro-menu",
			SHOW_BAR_TEXT = "Afficher le texte de la barre d’EXP/Réputation/Honneur",
			MAP_CLOCK = "Utiliser l’horloge de la carte en 24 h",
			SHOW_CHAT_BACKGROUND = "Afficher le fond du chat",
			
			VISIBILITY_TIP = "Voulez-vous afficher %s ?",
			STYLE_TIP = "Quel style voulez-vous pour %s ?",
			COLOR_TIP = "Quelle couleur voulez-vous pour %s ?",
			SIZE_TIP = "Quelle taille voulez-vous pour %s ?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Cochez-moi si vous voulez afficher %s dans %s.",
			CHECK_VISIBILITY_TIP = "Cochez-moi si vous voulez afficher %s.",
			CHECK_IF_YOU_WANT_TO_TIP = "Cochez-moi si vous voulez %s.",
			
			SLIDER_TEXT_OPACITY  = "Opacité : %d",
			SLIDER_TEXT_VISIBILITY = "Texte visible : %d s",
			SLIDER_TIP = "Vous pouvez aussi utiliser la molette de la souris ou les boutons latéraux pour modifier la valeur.",
			SLIDER_TEXT_HEIGHT = "Hauteur : %d",
			SLIDER_TEXT_WIDTH  = "Largeur : %d",
			
			P_TAB = "Profils",
			P_TITLE = "Créer, charger et supprimer des profils",
			P_SUB_CREATE = "Créer des profils",
			P_SUB_LOAD = "Charger des profils",
			P_SUB_DELETE = "Supprimer des profils",
			P_SUB_NOTES = "Notes",

			P_TIP_CREATE = "Entrez un nom de profil et appuyez sur Entrée pour enregistrer vos réglages.",
			P_TIP_LOAD = "Sélectionnez un profil à charger.",
			P_TIP_DELETE = "Sélectionnez un profil à supprimer.",

			P_WRN_NEED = "Veuillez entrer un nom de profil.",
			P_WRN_EXIST = "Ce profil existe déjà. Essayez un autre nom.",
			P_WRN_LOAD = "Aucun profil à charger.",
			P_WRN_DELETE = "Aucun profil à supprimer.",
		},
		deDE = {
			CLOSE_THIS_PANEL = "Dieses Panel schließen!",
			OPTIONS_FOR = "Optionen für %s",
			
			FOUR_EDGES = "Vier Kanten",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Fehlerfenster, FPS-Fenster usw.",
			ERROR_FRAME = "Fehlerfenster",
			FPS_FRAME = "FPS-Fenster",
			ET_CHETERA = "et cetera",
			ARTWORK = "Grafik",
			SIZE = "Größe",
			TOP_LEFT_EDGE_ARTWORK = "Grafik der oberen linken Kante",
			BOTTOM_LEFT_EDGE_ARTWORK = "Grafik der unteren linken Kante",
			TOP_RIGHT_EDGE_ARTWORK = "Grafik der oberen rechten Kante",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Grafik der unteren rechten Kante",
			BACKGROUND = "Hintergrund",
			FONTS = "Schriftarten",
			TITLE = "Titel",
			LOOT = "Beute",
			COINS = "Geld",
			CURRENCIES = "Währungen",
			EXPIRIENCE = "Erfahrung",
			HONOR = "Ehre",
			REPUTATION = "Ruf",
			SKILL = "Fertigkeit",
			MISCELLANEOUS = "Verschiedenes (Haltbarkeit, Öffnen usw.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Schriftarten des Fehlerfensters ändern",
			VISIBILITY = "Sichtbarkeit",
			STYLE = "Stil",
			COLOR = "Farbe",
			CHAT_BACKGROUND = "Chat-Hintergrund",
			WARNINGS = "Warnungen",
			ERRORS = "Fehler",
			SHOW_FPS = "FPS-Fenster anzeigen",
			SHOW_MICROMENU = "Hintergrund des Mikromenü-Containers anzeigen",
			SHOW_BAR_TEXT = "Text der EP-/Ruf-/Ehrenleiste anzeigen",
			MAP_CLOCK = "Kartenuhr im 24-Stunden-Format",
			SHOW_CHAT_BACKGROUND = "Chat-Hintergrund anzeigen",
			
			VISIBILITY_TIP = "Möchtest du %s anzeigen?",
			STYLE_TIP = "Welchen Stil möchtest du für %s?",
			COLOR_TIP = "Welche Farbe möchtest du für %s?",
			SIZE_TIP = "Welche Größe möchtest du für %s?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Aktiviere dies, wenn %s in %s angezeigt werden soll.",
			CHECK_VISIBILITY_TIP = "Aktiviere dies, wenn %s angezeigt werden soll.",
			CHECK_IF_YOU_WANT_TO_TIP = "Aktiviere dies, wenn du %s möchtest.",
			
			SLIDER_TEXT_OPACITY  = "Deckkraft: %d",
			SLIDER_TEXT_VISIBILITY = "Text sichtbar: %d Sek.",
			SLIDER_TIP = "Du kannst auch das Mausrad oder die seitlichen Buttons benutzen, um den Wert zu ändern.",
			SLIDER_TEXT_HEIGHT = "Höhe: %d",
			SLIDER_TEXT_WIDTH  = "Breite: %d",
			
			P_TAB = "Profile",
			P_TITLE = "Profile erstellen, laden und löschen",
			P_SUB_CREATE = "Profile erstellen",
			P_SUB_LOAD = "Profile laden",
			P_SUB_DELETE = "Profile löschen",
			P_SUB_NOTES = "Notizen",

			P_TIP_CREATE = "Profilnamen eingeben und Enter drücken, um deine Einstellungen zu speichern.",
			P_TIP_LOAD = "Wähle ein Profil zum Laden aus.",
			P_TIP_DELETE = "Wähle ein Profil zum Löschen aus.",

			P_WRN_NEED = "Bitte einen Profilnamen eingeben.",
			P_WRN_EXIST = "Dieses Profil existiert bereits. Bitte einen anderen Namen wählen.",
			P_WRN_LOAD = "Keine Profile zum Laden vorhanden.",
			P_WRN_DELETE = "Keine Profile zum Löschen vorhanden.",
		},
		esES = {
			CLOSE_THIS_PANEL = "¡Cerrar este panel!",
			OPTIONS_FOR = "Opciones de %s",
			
			FOUR_EDGES = "Cuatro bordes",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Marco de errores, marco de FPS, etc.",
			ERROR_FRAME = "Marco de errores",
			FPS_FRAME = "Marco de FPS",
			ET_CHETERA = "etcétera",
			ARTWORK = "Arte",
			SIZE = "Tamaño",
			TOP_LEFT_EDGE_ARTWORK = "Arte del borde superior izquierdo",
			BOTTOM_LEFT_EDGE_ARTWORK = "Arte del borde inferior izquierdo",
			TOP_RIGHT_EDGE_ARTWORK = "Arte del borde superior derecho",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Arte del borde inferior derecho",
			BACKGROUND = "Fondo",
			FONTS = "Fuentes",
			TITLE = "Título",
			LOOT = "Botín",
			COINS = "Dinero",
			CURRENCIES = "Monedas",
			EXPIRIENCE = "Experiencia",
			HONOR = "Honor",
			REPUTATION = "Reputación",
			SKILL = "Habilidad",
			MISCELLANEOUS = "Miscelánea (durabilidad, apertura, etc.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Cambiar las fuentes del marco de errores",
			VISIBILITY = "Visibilidad",
			STYLE = "Estilo",
			COLOR = "Color",
			CHAT_BACKGROUND = "Fondo del chat",
			WARNINGS = "Advertencias",
			ERRORS = "Errores",
			SHOW_FPS = "Mostrar marco de FPS",
			SHOW_MICROMENU = "Mostrar fondo del contenedor del micromenú",
			SHOW_BAR_TEXT = "Mostrar texto de la barra de EXP/Reputación/Honor",
			MAP_CLOCK = "Usar reloj del mapa en 24 horas",
			SHOW_CHAT_BACKGROUND = "Mostrar fondo del chat",
			
			VISIBILITY_TIP = "¿Quieres mostrar %s?",
			STYLE_TIP = "¿Qué estilo quieres para %s?",
			COLOR_TIP = "¿Qué color quieres para %s?",
			SIZE_TIP = "¿Qué tamaño quieres para %s?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Márcame si quieres que %s se muestre en %s.",
			CHECK_VISIBILITY_TIP = "Márcame si quieres que %s se muestre.",
			CHECK_IF_YOU_WANT_TO_TIP = "Márcame si quieres %s.",
			
			SLIDER_TEXT_OPACITY  = "Opacidad: %d",
			SLIDER_TEXT_VISIBILITY = "Texto visible: %d s",
			SLIDER_TIP = "También puedes usar la rueda del ratón o los botones laterales para cambiar el valor.",
			SLIDER_TEXT_HEIGHT = "Alto: %d",
			SLIDER_TEXT_WIDTH  = "Ancho: %d",
			
			P_TAB = "Perfiles",
			P_TITLE = "Crear, cargar y eliminar perfiles",
			P_SUB_CREATE = "Crear perfiles",
			P_SUB_LOAD = "Cargar perfiles",
			P_SUB_DELETE = "Eliminar perfiles",
			P_SUB_NOTES = "Notas",

			P_TIP_CREATE = "Escribe un nombre de perfil y pulsa Enter para guardar tus ajustes.",
			P_TIP_LOAD = "Selecciona un perfil para cargar.",
			P_TIP_DELETE = "Selecciona un perfil para eliminar.",

			P_WRN_NEED = "Por favor, escribe un nombre de perfil.",
			P_WRN_EXIST = "Ese perfil ya existe. Prueba con otro nombre.",
			P_WRN_LOAD = "No hay perfiles para cargar.",
			P_WRN_DELETE = "No hay perfiles para eliminar.",
		},
		itIT = {
			CLOSE_THIS_PANEL = "Chiudi questo pannello!",
			OPTIONS_FOR = "Opzioni per %s",
			
			FOUR_EDGES = "Quattro bordi",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Riquadro errori, riquadro FPS, ecc.",
			ERROR_FRAME = "Riquadro errori",
			FPS_FRAME = "Riquadro FPS",
			ET_CHETERA = "eccetera",
			ARTWORK = "Grafica",
			SIZE = "Dimensione",
			TOP_LEFT_EDGE_ARTWORK = "Grafica del bordo in alto a sinistra",
			BOTTOM_LEFT_EDGE_ARTWORK = "Grafica del bordo in basso a sinistra",
			TOP_RIGHT_EDGE_ARTWORK = "Grafica del bordo in alto a destra",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Grafica del bordo in basso a destra",
			BACKGROUND = "Sfondo",
			FONTS = "Caratteri",
			TITLE = "Titolo",
			LOOT = "Bottino",
			COINS = "Denaro",
			CURRENCIES = "Valute",
			EXPIRIENCE = "Esperienza",
			HONOR = "Onore",
			REPUTATION = "Reputazione",
			SKILL = "Abilità",
			MISCELLANEOUS = "Varie (durata, apertura, ecc.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Cambia i caratteri del riquadro errori",
			VISIBILITY = "Visibilità",
			STYLE = "Stile",
			COLOR = "Colore",
			CHAT_BACKGROUND = "Sfondo chat",
			WARNINGS = "Avvisi",
			ERRORS = "Errori",
			SHOW_FPS = "Mostra riquadro FPS",
			SHOW_MICROMENU = "Mostra sfondo del contenitore del micro menu",
			SHOW_BAR_TEXT = "Mostra testo della barra PE/Reputazione/Onore",
			MAP_CLOCK = "Usa l’orologio della mappa a 24 ore",
			SHOW_CHAT_BACKGROUND = "Mostra sfondo chat",
			
			VISIBILITY_TIP = "Vuoi mostrare %s?",
			STYLE_TIP = "Quale stile vuoi per %s?",
			COLOR_TIP = "Quale colore vuoi per %s?",
			SIZE_TIP = "Quale dimensione vuoi per %s?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Spuntami se vuoi mostrare %s in %s.",
			CHECK_VISIBILITY_TIP = "Spuntami se vuoi mostrare %s.",
			CHECK_IF_YOU_WANT_TO_TIP = "Spuntami se vuoi %s.",
			
			SLIDER_TEXT_OPACITY  = "Opacità: %d",
			SLIDER_TEXT_VISIBILITY = "Testo visibile: %d s",
			SLIDER_TIP = "Puoi anche usare la rotella del mouse o i pulsanti laterali per cambiare il valore.",
			SLIDER_TEXT_HEIGHT = "Altezza: %d",
			SLIDER_TEXT_WIDTH  = "Larghezza: %d",
			
			P_TAB = "Profili",
			P_TITLE = "Crea, carica ed elimina profili",
			P_SUB_CREATE = "Crea profili",
			P_SUB_LOAD = "Carica profili",
			P_SUB_DELETE = "Elimina profili",
			P_SUB_NOTES = "Note",

			P_TIP_CREATE = "Inserisci un nome profilo e premi Invio per salvare le impostazioni.",
			P_TIP_LOAD = "Seleziona un profilo da caricare.",
			P_TIP_DELETE = "Seleziona un profilo da eliminare.",

			P_WRN_NEED = "Inserisci un nome profilo.",
			P_WRN_EXIST = "Questo profilo esiste già. Prova un altro nome.",
			P_WRN_LOAD = "Non ci sono profili da caricare.",
			P_WRN_DELETE = "Non ci sono profili da eliminare.",
		},
		ruRU = {
			CLOSE_THIS_PANEL = "Закрыть эту панель!",
			OPTIONS_FOR = "Настройки для %s",
			
			FOUR_EDGES = "Четыре края",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "Окно ошибок, окно FPS и т. д.",
			ERROR_FRAME = "Окно ошибок",
			FPS_FRAME = "Окно FPS",
			ET_CHETERA = "и т. д.",
			ARTWORK = "Графика",
			SIZE = "Размер",
			TOP_LEFT_EDGE_ARTWORK = "Графика верхнего левого края",
			BOTTOM_LEFT_EDGE_ARTWORK = "Графика нижнего левого края",
			TOP_RIGHT_EDGE_ARTWORK = "Графика верхнего правого края",
			BOTTOM_RIGHT_EDGE_ARTWORK = "Графика нижнего правого края",
			BACKGROUND = "Фон",
			FONTS = "Шрифты",
			TITLE = "Заголовок",
			LOOT = "Добыча",
			COINS = "Деньги",
			CURRENCIES = "Валюты",
			EXPIRIENCE = "Опыт",
			HONOR = "Честь",
			REPUTATION = "Репутация",
			SKILL = "Навык",
			MISCELLANEOUS = "Разное (прочность, открытие и т. д.)",
			CHANGE_THE_ERROR_FRAME_FONTS = "Изменить шрифты окна ошибок",
			VISIBILITY = "Видимость",
			STYLE = "Стиль",
			COLOR = "Цвет",
			CHAT_BACKGROUND = "Фон чата",
			WARNINGS = "Предупреждения",
			ERRORS = "Ошибки",
			SHOW_FPS = "Показывать окно FPS",
			SHOW_MICROMENU = "Показывать фон контейнера микроменю",
			SHOW_BAR_TEXT = "Показывать текст полосы опыта/репутации/чести",
			MAP_CLOCK = "Использовать 24-часовые часы на карте",
			SHOW_CHAT_BACKGROUND = "Показывать фон чата",
			
			VISIBILITY_TIP = "Показывать %s?",
			STYLE_TIP = "Какой стиль вы хотите для %s?",
			COLOR_TIP = "Какой цвет вы хотите для %s?",
			SIZE_TIP = "Какой размер вы хотите для %s?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "Отметьте, если хотите показывать %s в %s.",
			CHECK_VISIBILITY_TIP = "Отметьте, если хотите показывать %s.",
			CHECK_IF_YOU_WANT_TO_TIP = "Отметьте, если хотите %s.",
			
			SLIDER_TEXT_OPACITY  = "Непрозрачность: %d",
			SLIDER_TEXT_VISIBILITY = "Видимость текста: %d сек.",
			SLIDER_TIP = "Вы также можете использовать колесо мыши или кнопки по краям, чтобы изменить значение.",
			SLIDER_TEXT_HEIGHT = "Высота: %d",
			SLIDER_TEXT_WIDTH  = "Ширина: %d",
			
			P_TAB = "Профили",
			P_TITLE = "Создание, загрузка и удаление профилей",
			P_SUB_CREATE = "Создать профиль",
			P_SUB_LOAD = "Загрузить профиль",
			P_SUB_DELETE = "Удалить профиль",
			P_SUB_NOTES = "Заметки",

			P_TIP_CREATE = "Введите имя профиля и нажмите Enter, чтобы сохранить настройки.",
			P_TIP_LOAD = "Выберите профиль для загрузки.",
			P_TIP_DELETE = "Выберите профиль для удаления.",

			P_WRN_NEED = "Пожалуйста, введите имя профиля.",
			P_WRN_EXIST = "Такой профиль уже существует. Попробуйте другое имя.",
			P_WRN_LOAD = "Нет профилей для загрузки.",
			P_WRN_DELETE = "Нет профилей для удаления.",
		},
		zhCN = {
			CLOSE_THIS_PANEL = "关闭此面板！",
			OPTIONS_FOR = "%s 选项",
			
			FOUR_EDGES = "四边",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "错误框体、FPS 框体等",
			ERROR_FRAME = "错误框体",
			FPS_FRAME = "FPS 框体",
			ET_CHETERA = "等等",
			ARTWORK = "美术",
			SIZE = "大小",
			TOP_LEFT_EDGE_ARTWORK = "左上边缘美术",
			BOTTOM_LEFT_EDGE_ARTWORK = "左下边缘美术",
			TOP_RIGHT_EDGE_ARTWORK = "右上边缘美术",
			BOTTOM_RIGHT_EDGE_ARTWORK = "右下边缘美术",
			BACKGROUND = "背景",
			FONTS = "字体",
			TITLE = "标题",
			LOOT = "拾取",
			COINS = "金钱",
			CURRENCIES = "货币",
			EXPIRIENCE = "经验",
			HONOR = "荣誉",
			REPUTATION = "声望",
			SKILL = "技能",
			MISCELLANEOUS = "杂项（耐久、打开等）",
			CHANGE_THE_ERROR_FRAME_FONTS = "更改错误框体字体",
			VISIBILITY = "可见性",
			STYLE = "样式",
			COLOR = "颜色",
			CHAT_BACKGROUND = "聊天背景",
			WARNINGS = "警告",
			ERRORS = "错误",
			SHOW_FPS = "显示 FPS 框体",
			SHOW_MICROMENU = "显示微型菜单容器背景",
			SHOW_BAR_TEXT = "显示经验/声望/荣誉条文本",
			MAP_CLOCK = "地图时钟使用24小时制",
			SHOW_CHAT_BACKGROUND = "显示聊天背景",
			
			VISIBILITY_TIP = "你想显示 %s 吗？",
			STYLE_TIP = "你想为 %s 使用哪种样式？",
			COLOR_TIP = "你想为 %s 使用哪种颜色？",
			SIZE_TIP = "你想为 %s 使用多大尺寸？",
			
			CHECK_VISIBILITY_TIP_IN_THE = "如果你想在 %s 中显示 %s，就勾选我。",
			CHECK_VISIBILITY_TIP = "如果你想显示 %s，就勾选我。",
			CHECK_IF_YOU_WANT_TO_TIP = "如果你想 %s，就勾选我。",
			
			SLIDER_TEXT_OPACITY  = "不透明度：%d",
			SLIDER_TEXT_VISIBILITY = "文本可见时间：%d 秒",
			SLIDER_TIP = "你也可以使用鼠标滚轮或两侧按钮来调整数值。",
			SLIDER_TEXT_HEIGHT = "高度：%d",
			SLIDER_TEXT_WIDTH  = "宽度：%d",
			
			P_TAB = "配置文件",
			P_TITLE = "创建、载入、删除配置文件",
			P_SUB_CREATE = "创建配置",
			P_SUB_LOAD = "载入配置",
			P_SUB_DELETE = "删除配置",
			P_SUB_NOTES = "备注",

			P_TIP_CREATE = "输入配置名称并按 Enter 保存设置。",
			P_TIP_LOAD = "选择一个配置以载入。",
			P_TIP_DELETE = "选择一个配置以删除。",

			P_WRN_NEED = "请输入配置名称。",
			P_WRN_EXIST = "该配置已存在。请换一个名称。",
			P_WRN_LOAD = "没有可载入的配置。",
			P_WRN_DELETE = "没有可删除的配置。",
		},
		zhTW = {
			CLOSE_THIS_PANEL = "關閉此面板！",
			OPTIONS_FOR = "%s 選項",
			
			FOUR_EDGES = "四邊",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "錯誤框體、FPS 框體等",
			ERROR_FRAME = "錯誤框體",
			FPS_FRAME = "FPS 框體",
			ET_CHETERA = "等等",
			ARTWORK = "美術",
			SIZE = "大小",
			TOP_LEFT_EDGE_ARTWORK = "左上邊緣美術",
			BOTTOM_LEFT_EDGE_ARTWORK = "左下邊緣美術",
			TOP_RIGHT_EDGE_ARTWORK = "右上邊緣美術",
			BOTTOM_RIGHT_EDGE_ARTWORK = "右下邊緣美術",
			BACKGROUND = "背景",
			FONTS = "字型",
			TITLE = "標題",
			LOOT = "拾取",
			COINS = "金錢",
			CURRENCIES = "貨幣",
			EXPIRIENCE = "經驗",
			HONOR = "榮譽",
			REPUTATION = "聲望",
			SKILL = "技能",
			MISCELLANEOUS = "雜項（耐久、打開等）",
			CHANGE_THE_ERROR_FRAME_FONTS = "更改錯誤框體字型",
			VISIBILITY = "可見性",
			STYLE = "樣式",
			COLOR = "顏色",
			CHAT_BACKGROUND = "聊天背景",
			WARNINGS = "警告",
			ERRORS = "錯誤",
			SHOW_FPS = "顯示 FPS 框架",
			SHOW_MICROMENU = "顯示微型選單容器背景",
			SHOW_BAR_TEXT = "顯示經驗/聲望/榮譽條文字",
			MAP_CLOCK = "地圖時鐘使用 24 小時制",
			SHOW_CHAT_BACKGROUND = "顯示聊天背景",
			
			VISIBILITY_TIP = "你想顯示 %s 嗎？",
			STYLE_TIP = "你想為 %s 使用哪種樣式？",
			COLOR_TIP = "你想為 %s 使用哪種顏色？",
			SIZE_TIP = "你想為 %s 使用多大尺寸？",
			
			CHECK_VISIBILITY_TIP_IN_THE = "如果你想在 %s 中顯示 %s，就勾選我。",
			CHECK_VISIBILITY_TIP = "如果你想顯示 %s，就勾選我。",
			CHECK_IF_YOU_WANT_TO_TIP = "如果你想 %s，就勾選我。",
			
			SLIDER_TEXT_OPACITY  = "不透明度：%d",
			SLIDER_TEXT_VISIBILITY = "文字可見時間：%d 秒",
			SLIDER_TIP = "你也可以使用滑鼠滾輪或兩側按鈕來調整數值。",
			SLIDER_TEXT_HEIGHT = "高度：%d",
			SLIDER_TEXT_WIDTH  = "寬度：%d",
			
			P_TAB = "設定檔",
			P_TITLE = "建立、載入、刪除設定檔",
			P_SUB_CREATE = "建立設定檔",
			P_SUB_LOAD = "載入設定檔",
			P_SUB_DELETE = "刪除設定檔",
			P_SUB_NOTES = "備註",

			P_TIP_CREATE = "輸入設定檔名稱並按 Enter 以儲存設定。",
			P_TIP_LOAD = "選擇要載入的設定檔。",
			P_TIP_DELETE = "選擇要刪除的設定檔。",

			P_WRN_NEED = "請輸入設定檔名稱。",
			P_WRN_EXIST = "此設定檔已存在。請換一個名稱。",
			P_WRN_LOAD = "沒有可載入的設定檔。",
			P_WRN_DELETE = "沒有可刪除的設定檔。",
		},
		koKR = {
			CLOSE_THIS_PANEL = "이 패널 닫기!",
			OPTIONS_FOR = "%s 옵션",
			
			FOUR_EDGES = "네 가장자리",
			LOOTY_GROOVE = "Looty Groove",
			ERROR_FRAME_FPS = "오류 프레임, FPS 프레임 등",
			ERROR_FRAME = "오류 프레임",
			FPS_FRAME = "FPS 프레임",
			ET_CHETERA = "기타",
			ARTWORK = "아트워크",
			SIZE = "크기",
			TOP_LEFT_EDGE_ARTWORK = "왼쪽 위 가장자리 아트워크",
			BOTTOM_LEFT_EDGE_ARTWORK = "왼쪽 아래 가장자리 아트워크",
			TOP_RIGHT_EDGE_ARTWORK = "오른쪽 위 가장자리 아트워크",
			BOTTOM_RIGHT_EDGE_ARTWORK = "오른쪽 아래 가장자리 아트워크",
			BACKGROUND = "배경",
			FONTS = "글꼴",
			TITLE = "제목",
			LOOT = "전리품",
			COINS = "돈",
			CURRENCIES = "화폐",
			EXPIRIENCE = "경험치",
			HONOR = "명예",
			REPUTATION = "평판",
			SKILL = "기술",
			MISCELLANEOUS = "기타(내구도, 열기 등)",
			CHANGE_THE_ERROR_FRAME_FONTS = "오류 프레임 글꼴 변경",
			VISIBILITY = "표시",
			STYLE = "스타일",
			COLOR = "색상",
			CHAT_BACKGROUND = "채팅 배경",
			WARNINGS = "경고",
			ERRORS = "오류",
			SHOW_FPS = "FPS 프레임 표시",
			SHOW_MICROMENU = "마이크로 메뉴 컨테이너 배경 표시",
			SHOW_BAR_TEXT = "경험치/평판/명예 바 텍스트 표시",
			MAP_CLOCK = "지도 시계를 24시간제로 사용",
			SHOW_CHAT_BACKGROUND = "채팅 배경 표시",
			
			VISIBILITY_TIP = "%s을(를) 표시할까요?",
			STYLE_TIP = "%s에 어떤 스타일을 원하시나요?",
			COLOR_TIP = "%s에 어떤 색상을 원하시나요?",
			SIZE_TIP = "%s에 어떤 크기를 원하시나요?",
			
			CHECK_VISIBILITY_TIP_IN_THE = "체크하면 %s이(가) %s에 표시됩니다.",
			CHECK_VISIBILITY_TIP = "체크하면 %s이(가) 표시됩니다.",
			CHECK_IF_YOU_WANT_TO_TIP = "%s하려면 체크하세요.",
			
			SLIDER_TEXT_OPACITY  = "투명도: %d",
			SLIDER_TEXT_VISIBILITY = "텍스트 표시 시간: %d초",
			SLIDER_TIP = "마우스 휠이나 양쪽 버튼으로 값도 변경할 수 있습니다.",
			SLIDER_TEXT_HEIGHT = "높이: %d",
			SLIDER_TEXT_WIDTH  = "너비: %d",
			
			P_TAB = "프로필",
			P_TITLE = "프로필 생성/불러오기/삭제",
			P_SUB_CREATE = "프로필 생성",
			P_SUB_LOAD = "프로필 불러오기",
			P_SUB_DELETE = "프로필 삭제",
			P_SUB_NOTES = "메모",

			P_TIP_CREATE = "프로필 이름을 입력하고 Enter를 눌러 설정을 저장하세요.",
			P_TIP_LOAD = "불러올 프로필을 선택하세요.",
			P_TIP_DELETE = "삭제할 프로필을 선택하세요.",

			P_WRN_NEED = "프로필 이름을 입력하세요.",
			P_WRN_EXIST = "이미 존재하는 프로필입니다. 다른 이름을 사용하세요.",
			P_WRN_LOAD = "불러올 프로필이 없습니다.",
			P_WRN_DELETE = "삭제할 프로필이 없습니다.",
		},
	}
	local loc = GetLocale()
	local ov = o[loc]
	if type(ov) == "string" then ov = o[ov] end
	if ov then
		for k, v in pairs(ov) do base[k] = v end
	end
	return base
end)()
